/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHarnessesRouteImport } from './routes/api.harnesses'
import { Route as ApiSettingsRouteImport } from './routes/api.settings'
import { Route as ApiAssistPromptsRouteImport } from './routes/api.assist.prompts'
import { Route as ApiAssistSimpleRouteImport } from './routes/api.assist.simple'
import { Route as ApiImagesGenerateRouteImport } from './routes/api.images.generate'
import { Route as ApiImagesLogsRouteImport } from './routes/api.images.logs'
import { Route as ApiImagesRevealRouteImport } from './routes/api.images.reveal'
import { Route as ApiImagesStylesRouteImport } from './routes/api.images.styles'
import { Route as ApiSettingsEnvDefaultRouteImport } from './routes/api.settings.env-default'
import { Route as ApiSettingsTestEndpointRouteImport } from './routes/api.settings.test-endpoint'
import { Route as ApiSettingsTestImageProviderRouteImport } from './routes/api.settings.test-image-provider'
import { Route as ApiWorkspaceBrowseRouteImport } from './routes/api.workspace.browse'
import { Route as ApiWorkspaceCreateRouteImport } from './routes/api.workspace.create'
import { Route as ApiWorkspaceFilesRouteImport } from './routes/api.workspace.files'
import { Route as ApiWorkspaceGitRouteImport } from './routes/api.workspace.git'
import { Route as ApiWorkspaceGitInitRouteImport } from './routes/api.workspace.git-init'
import { Route as ApiWorkspaceGitStatusRouteImport } from './routes/api.workspace.git-status'
import { Route as ApiWorkspaceGitTrackedRouteImport } from './routes/api.workspace.git-tracked'
import { Route as ApiWorkspaceLinkRouteImport } from './routes/api.workspace.link'
import { Route as ApiWorkspaceMediaRouteImport } from './routes/api.workspace.media'
import { Route as ApiWorkspaceProfilesRouteImport } from './routes/api.workspace.profiles'
import { Route as ApiWorkspaceStatsRouteImport } from './routes/api.workspace.stats'
import { Route as ApiWorkspaceStylesRouteImport } from './routes/api.workspace.styles'
import { Route as ApiAssistPromptsSplatRouteImport } from './routes/api.assist.prompts.$'
import { Route as ApiAssistSimpleLogsRouteImport } from './routes/api.assist.simple.logs'
import { Route as ApiHarnessesIdModelsRouteImport } from './routes/api.harnesses.$id.models'
import { Route as ApiImagesComfyAnalyzeRouteImport } from './routes/api.images.comfy.analyze'
import { Route as ApiImagesLogsSplatRouteImport } from './routes/api.images.logs.$'
import { Route as ApiWorkspaceFilesSplatRouteImport } from './routes/api.workspace.files.$'
import { Route as ApiWorkspaceFoldersSplatRouteImport } from './routes/api.workspace.folders.$'
import { Route as ApiWorkspaceMediaSplatRouteImport } from './routes/api.workspace.media.$'
import { Route as ApiWorkspaceMediaFromUrlRouteImport } from './routes/api.workspace.media.from-url'
import { Route as ApiWorkspaceProfilesIdRouteImport } from './routes/api.workspace.profiles.$id'
import { Route as ApiAssistSimpleSessionSplatRouteImport } from './routes/api.assist.simple.session.$'
import { Route as ApiAssistSimpleStopSplatRouteImport } from './routes/api.assist.simple.stop.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHarnessesRoute = ApiHarnessesRouteImport.update({
  id: '/api/harnesses',
  path: '/api/harnesses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistPromptsRoute = ApiAssistPromptsRouteImport.update({
  id: '/api/assist/prompts',
  path: '/api/assist/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistSimpleRoute = ApiAssistSimpleRouteImport.update({
  id: '/api/assist/simple',
  path: '/api/assist/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesGenerateRoute = ApiImagesGenerateRouteImport.update({
  id: '/api/images/generate',
  path: '/api/images/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesLogsRoute = ApiImagesLogsRouteImport.update({
  id: '/api/images/logs',
  path: '/api/images/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesRevealRoute = ApiImagesRevealRouteImport.update({
  id: '/api/images/reveal',
  path: '/api/images/reveal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesStylesRoute = ApiImagesStylesRouteImport.update({
  id: '/api/images/styles',
  path: '/api/images/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsEnvDefaultRoute = ApiSettingsEnvDefaultRouteImport.update({
  id: '/env-default',
  path: '/env-default',
  getParentRoute: () => ApiSettingsRoute,
} as any)
const ApiSettingsTestEndpointRoute = ApiSettingsTestEndpointRouteImport.update({
  id: '/test-endpoint',
  path: '/test-endpoint',
  getParentRoute: () => ApiSettingsRoute,
} as any)
const ApiSettingsTestImageProviderRoute =
  ApiSettingsTestImageProviderRouteImport.update({
    id: '/test-image-provider',
    path: '/test-image-provider',
    getParentRoute: () => ApiSettingsRoute,
  } as any)
const ApiWorkspaceBrowseRoute = ApiWorkspaceBrowseRouteImport.update({
  id: '/api/workspace/browse',
  path: '/api/workspace/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceCreateRoute = ApiWorkspaceCreateRouteImport.update({
  id: '/api/workspace/create',
  path: '/api/workspace/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceFilesRoute = ApiWorkspaceFilesRouteImport.update({
  id: '/api/workspace/files',
  path: '/api/workspace/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceGitRoute = ApiWorkspaceGitRouteImport.update({
  id: '/api/workspace/git',
  path: '/api/workspace/git',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceGitInitRoute = ApiWorkspaceGitInitRouteImport.update({
  id: '/api/workspace/git-init',
  path: '/api/workspace/git-init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceGitStatusRoute = ApiWorkspaceGitStatusRouteImport.update({
  id: '/api/workspace/git-status',
  path: '/api/workspace/git-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceGitTrackedRoute = ApiWorkspaceGitTrackedRouteImport.update({
  id: '/api/workspace/git-tracked',
  path: '/api/workspace/git-tracked',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceLinkRoute = ApiWorkspaceLinkRouteImport.update({
  id: '/api/workspace/link',
  path: '/api/workspace/link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceMediaRoute = ApiWorkspaceMediaRouteImport.update({
  id: '/api/workspace/media',
  path: '/api/workspace/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceProfilesRoute = ApiWorkspaceProfilesRouteImport.update({
  id: '/api/workspace/profiles',
  path: '/api/workspace/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceStatsRoute = ApiWorkspaceStatsRouteImport.update({
  id: '/api/workspace/stats',
  path: '/api/workspace/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceStylesRoute = ApiWorkspaceStylesRouteImport.update({
  id: '/api/workspace/styles',
  path: '/api/workspace/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistPromptsSplatRoute = ApiAssistPromptsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiAssistPromptsRoute,
} as any)
const ApiAssistSimpleLogsRoute = ApiAssistSimpleLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ApiAssistSimpleRoute,
} as any)
const ApiHarnessesIdModelsRoute = ApiHarnessesIdModelsRouteImport.update({
  id: '/$id/models',
  path: '/$id/models',
  getParentRoute: () => ApiHarnessesRoute,
} as any)
const ApiImagesComfyAnalyzeRoute = ApiImagesComfyAnalyzeRouteImport.update({
  id: '/api/images/comfy/analyze',
  path: '/api/images/comfy/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesLogsSplatRoute = ApiImagesLogsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiImagesLogsRoute,
} as any)
const ApiWorkspaceFilesSplatRoute = ApiWorkspaceFilesSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiWorkspaceFilesRoute,
} as any)
const ApiWorkspaceFoldersSplatRoute =
  ApiWorkspaceFoldersSplatRouteImport.update({
    id: '/api/workspace/folders/$',
    path: '/api/workspace/folders/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkspaceMediaSplatRoute = ApiWorkspaceMediaSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiWorkspaceMediaRoute,
} as any)
const ApiWorkspaceMediaFromUrlRoute =
  ApiWorkspaceMediaFromUrlRouteImport.update({
    id: '/from-url',
    path: '/from-url',
    getParentRoute: () => ApiWorkspaceMediaRoute,
  } as any)
const ApiWorkspaceProfilesIdRoute = ApiWorkspaceProfilesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWorkspaceProfilesRoute,
} as any)
const ApiAssistSimpleSessionSplatRoute =
  ApiAssistSimpleSessionSplatRouteImport.update({
    id: '/session/$',
    path: '/session/$',
    getParentRoute: () => ApiAssistSimpleRoute,
  } as any)
const ApiAssistSimpleStopSplatRoute =
  ApiAssistSimpleStopSplatRouteImport.update({
    id: '/stop/$',
    path: '/stop/$',
    getParentRoute: () => ApiAssistSimpleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/harnesses': typeof ApiHarnessesRouteWithChildren
  '/api/settings': typeof ApiSettingsRouteWithChildren
  '/api/assist/prompts': typeof ApiAssistPromptsRouteWithChildren
  '/api/assist/simple': typeof ApiAssistSimpleRouteWithChildren
  '/api/images/generate': typeof ApiImagesGenerateRoute
  '/api/images/logs': typeof ApiImagesLogsRouteWithChildren
  '/api/images/reveal': typeof ApiImagesRevealRoute
  '/api/images/styles': typeof ApiImagesStylesRoute
  '/api/settings/env-default': typeof ApiSettingsEnvDefaultRoute
  '/api/settings/test-endpoint': typeof ApiSettingsTestEndpointRoute
  '/api/settings/test-image-provider': typeof ApiSettingsTestImageProviderRoute
  '/api/workspace/browse': typeof ApiWorkspaceBrowseRoute
  '/api/workspace/create': typeof ApiWorkspaceCreateRoute
  '/api/workspace/files': typeof ApiWorkspaceFilesRouteWithChildren
  '/api/workspace/git': typeof ApiWorkspaceGitRoute
  '/api/workspace/git-init': typeof ApiWorkspaceGitInitRoute
  '/api/workspace/git-status': typeof ApiWorkspaceGitStatusRoute
  '/api/workspace/git-tracked': typeof ApiWorkspaceGitTrackedRoute
  '/api/workspace/link': typeof ApiWorkspaceLinkRoute
  '/api/workspace/media': typeof ApiWorkspaceMediaRouteWithChildren
  '/api/workspace/profiles': typeof ApiWorkspaceProfilesRouteWithChildren
  '/api/workspace/stats': typeof ApiWorkspaceStatsRoute
  '/api/workspace/styles': typeof ApiWorkspaceStylesRoute
  '/api/assist/prompts/$': typeof ApiAssistPromptsSplatRoute
  '/api/assist/simple/logs': typeof ApiAssistSimpleLogsRoute
  '/api/harnesses/$id/models': typeof ApiHarnessesIdModelsRoute
  '/api/images/comfy/analyze': typeof ApiImagesComfyAnalyzeRoute
  '/api/images/logs/$': typeof ApiImagesLogsSplatRoute
  '/api/workspace/files/$': typeof ApiWorkspaceFilesSplatRoute
  '/api/workspace/folders/$': typeof ApiWorkspaceFoldersSplatRoute
  '/api/workspace/media/$': typeof ApiWorkspaceMediaSplatRoute
  '/api/workspace/media/from-url': typeof ApiWorkspaceMediaFromUrlRoute
  '/api/workspace/profiles/$id': typeof ApiWorkspaceProfilesIdRoute
  '/api/assist/simple/session/$': typeof ApiAssistSimpleSessionSplatRoute
  '/api/assist/simple/stop/$': typeof ApiAssistSimpleStopSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/harnesses': typeof ApiHarnessesRouteWithChildren
  '/api/settings': typeof ApiSettingsRouteWithChildren
  '/api/assist/prompts': typeof ApiAssistPromptsRouteWithChildren
  '/api/assist/simple': typeof ApiAssistSimpleRouteWithChildren
  '/api/images/generate': typeof ApiImagesGenerateRoute
  '/api/images/logs': typeof ApiImagesLogsRouteWithChildren
  '/api/images/reveal': typeof ApiImagesRevealRoute
  '/api/images/styles': typeof ApiImagesStylesRoute
  '/api/settings/env-default': typeof ApiSettingsEnvDefaultRoute
  '/api/settings/test-endpoint': typeof ApiSettingsTestEndpointRoute
  '/api/settings/test-image-provider': typeof ApiSettingsTestImageProviderRoute
  '/api/workspace/browse': typeof ApiWorkspaceBrowseRoute
  '/api/workspace/create': typeof ApiWorkspaceCreateRoute
  '/api/workspace/files': typeof ApiWorkspaceFilesRouteWithChildren
  '/api/workspace/git': typeof ApiWorkspaceGitRoute
  '/api/workspace/git-init': typeof ApiWorkspaceGitInitRoute
  '/api/workspace/git-status': typeof ApiWorkspaceGitStatusRoute
  '/api/workspace/git-tracked': typeof ApiWorkspaceGitTrackedRoute
  '/api/workspace/link': typeof ApiWorkspaceLinkRoute
  '/api/workspace/media': typeof ApiWorkspaceMediaRouteWithChildren
  '/api/workspace/profiles': typeof ApiWorkspaceProfilesRouteWithChildren
  '/api/workspace/stats': typeof ApiWorkspaceStatsRoute
  '/api/workspace/styles': typeof ApiWorkspaceStylesRoute
  '/api/assist/prompts/$': typeof ApiAssistPromptsSplatRoute
  '/api/assist/simple/logs': typeof ApiAssistSimpleLogsRoute
  '/api/harnesses/$id/models': typeof ApiHarnessesIdModelsRoute
  '/api/images/comfy/analyze': typeof ApiImagesComfyAnalyzeRoute
  '/api/images/logs/$': typeof ApiImagesLogsSplatRoute
  '/api/workspace/files/$': typeof ApiWorkspaceFilesSplatRoute
  '/api/workspace/folders/$': typeof ApiWorkspaceFoldersSplatRoute
  '/api/workspace/media/$': typeof ApiWorkspaceMediaSplatRoute
  '/api/workspace/media/from-url': typeof ApiWorkspaceMediaFromUrlRoute
  '/api/workspace/profiles/$id': typeof ApiWorkspaceProfilesIdRoute
  '/api/assist/simple/session/$': typeof ApiAssistSimpleSessionSplatRoute
  '/api/assist/simple/stop/$': typeof ApiAssistSimpleStopSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/harnesses': typeof ApiHarnessesRouteWithChildren
  '/api/settings': typeof ApiSettingsRouteWithChildren
  '/api/assist/prompts': typeof ApiAssistPromptsRouteWithChildren
  '/api/assist/simple': typeof ApiAssistSimpleRouteWithChildren
  '/api/images/generate': typeof ApiImagesGenerateRoute
  '/api/images/logs': typeof ApiImagesLogsRouteWithChildren
  '/api/images/reveal': typeof ApiImagesRevealRoute
  '/api/images/styles': typeof ApiImagesStylesRoute
  '/api/settings/env-default': typeof ApiSettingsEnvDefaultRoute
  '/api/settings/test-endpoint': typeof ApiSettingsTestEndpointRoute
  '/api/settings/test-image-provider': typeof ApiSettingsTestImageProviderRoute
  '/api/workspace/browse': typeof ApiWorkspaceBrowseRoute
  '/api/workspace/create': typeof ApiWorkspaceCreateRoute
  '/api/workspace/files': typeof ApiWorkspaceFilesRouteWithChildren
  '/api/workspace/git': typeof ApiWorkspaceGitRoute
  '/api/workspace/git-init': typeof ApiWorkspaceGitInitRoute
  '/api/workspace/git-status': typeof ApiWorkspaceGitStatusRoute
  '/api/workspace/git-tracked': typeof ApiWorkspaceGitTrackedRoute
  '/api/workspace/link': typeof ApiWorkspaceLinkRoute
  '/api/workspace/media': typeof ApiWorkspaceMediaRouteWithChildren
  '/api/workspace/profiles': typeof ApiWorkspaceProfilesRouteWithChildren
  '/api/workspace/stats': typeof ApiWorkspaceStatsRoute
  '/api/workspace/styles': typeof ApiWorkspaceStylesRoute
  '/api/assist/prompts/$': typeof ApiAssistPromptsSplatRoute
  '/api/assist/simple/logs': typeof ApiAssistSimpleLogsRoute
  '/api/harnesses/$id/models': typeof ApiHarnessesIdModelsRoute
  '/api/images/comfy/analyze': typeof ApiImagesComfyAnalyzeRoute
  '/api/images/logs/$': typeof ApiImagesLogsSplatRoute
  '/api/workspace/files/$': typeof ApiWorkspaceFilesSplatRoute
  '/api/workspace/folders/$': typeof ApiWorkspaceFoldersSplatRoute
  '/api/workspace/media/$': typeof ApiWorkspaceMediaSplatRoute
  '/api/workspace/media/from-url': typeof ApiWorkspaceMediaFromUrlRoute
  '/api/workspace/profiles/$id': typeof ApiWorkspaceProfilesIdRoute
  '/api/assist/simple/session/$': typeof ApiAssistSimpleSessionSplatRoute
  '/api/assist/simple/stop/$': typeof ApiAssistSimpleStopSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/harnesses'
    | '/api/settings'
    | '/api/assist/prompts'
    | '/api/assist/simple'
    | '/api/images/generate'
    | '/api/images/logs'
    | '/api/images/reveal'
    | '/api/images/styles'
    | '/api/settings/env-default'
    | '/api/settings/test-endpoint'
    | '/api/settings/test-image-provider'
    | '/api/workspace/browse'
    | '/api/workspace/create'
    | '/api/workspace/files'
    | '/api/workspace/git'
    | '/api/workspace/git-init'
    | '/api/workspace/git-status'
    | '/api/workspace/git-tracked'
    | '/api/workspace/link'
    | '/api/workspace/media'
    | '/api/workspace/profiles'
    | '/api/workspace/stats'
    | '/api/workspace/styles'
    | '/api/assist/prompts/$'
    | '/api/assist/simple/logs'
    | '/api/harnesses/$id/models'
    | '/api/images/comfy/analyze'
    | '/api/images/logs/$'
    | '/api/workspace/files/$'
    | '/api/workspace/folders/$'
    | '/api/workspace/media/$'
    | '/api/workspace/media/from-url'
    | '/api/workspace/profiles/$id'
    | '/api/assist/simple/session/$'
    | '/api/assist/simple/stop/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/harnesses'
    | '/api/settings'
    | '/api/assist/prompts'
    | '/api/assist/simple'
    | '/api/images/generate'
    | '/api/images/logs'
    | '/api/images/reveal'
    | '/api/images/styles'
    | '/api/settings/env-default'
    | '/api/settings/test-endpoint'
    | '/api/settings/test-image-provider'
    | '/api/workspace/browse'
    | '/api/workspace/create'
    | '/api/workspace/files'
    | '/api/workspace/git'
    | '/api/workspace/git-init'
    | '/api/workspace/git-status'
    | '/api/workspace/git-tracked'
    | '/api/workspace/link'
    | '/api/workspace/media'
    | '/api/workspace/profiles'
    | '/api/workspace/stats'
    | '/api/workspace/styles'
    | '/api/assist/prompts/$'
    | '/api/assist/simple/logs'
    | '/api/harnesses/$id/models'
    | '/api/images/comfy/analyze'
    | '/api/images/logs/$'
    | '/api/workspace/files/$'
    | '/api/workspace/folders/$'
    | '/api/workspace/media/$'
    | '/api/workspace/media/from-url'
    | '/api/workspace/profiles/$id'
    | '/api/assist/simple/session/$'
    | '/api/assist/simple/stop/$'
  id:
    | '__root__'
    | '/'
    | '/api/harnesses'
    | '/api/settings'
    | '/api/assist/prompts'
    | '/api/assist/simple'
    | '/api/images/generate'
    | '/api/images/logs'
    | '/api/images/reveal'
    | '/api/images/styles'
    | '/api/settings/env-default'
    | '/api/settings/test-endpoint'
    | '/api/settings/test-image-provider'
    | '/api/workspace/browse'
    | '/api/workspace/create'
    | '/api/workspace/files'
    | '/api/workspace/git'
    | '/api/workspace/git-init'
    | '/api/workspace/git-status'
    | '/api/workspace/git-tracked'
    | '/api/workspace/link'
    | '/api/workspace/media'
    | '/api/workspace/profiles'
    | '/api/workspace/stats'
    | '/api/workspace/styles'
    | '/api/assist/prompts/$'
    | '/api/assist/simple/logs'
    | '/api/harnesses/$id/models'
    | '/api/images/comfy/analyze'
    | '/api/images/logs/$'
    | '/api/workspace/files/$'
    | '/api/workspace/folders/$'
    | '/api/workspace/media/$'
    | '/api/workspace/media/from-url'
    | '/api/workspace/profiles/$id'
    | '/api/assist/simple/session/$'
    | '/api/assist/simple/stop/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHarnessesRoute: typeof ApiHarnessesRouteWithChildren
  ApiSettingsRoute: typeof ApiSettingsRouteWithChildren
  ApiAssistPromptsRoute: typeof ApiAssistPromptsRouteWithChildren
  ApiAssistSimpleRoute: typeof ApiAssistSimpleRouteWithChildren
  ApiImagesGenerateRoute: typeof ApiImagesGenerateRoute
  ApiImagesLogsRoute: typeof ApiImagesLogsRouteWithChildren
  ApiImagesRevealRoute: typeof ApiImagesRevealRoute
  ApiImagesStylesRoute: typeof ApiImagesStylesRoute
  ApiWorkspaceBrowseRoute: typeof ApiWorkspaceBrowseRoute
  ApiWorkspaceCreateRoute: typeof ApiWorkspaceCreateRoute
  ApiWorkspaceFilesRoute: typeof ApiWorkspaceFilesRouteWithChildren
  ApiWorkspaceGitRoute: typeof ApiWorkspaceGitRoute
  ApiWorkspaceGitInitRoute: typeof ApiWorkspaceGitInitRoute
  ApiWorkspaceGitStatusRoute: typeof ApiWorkspaceGitStatusRoute
  ApiWorkspaceGitTrackedRoute: typeof ApiWorkspaceGitTrackedRoute
  ApiWorkspaceLinkRoute: typeof ApiWorkspaceLinkRoute
  ApiWorkspaceMediaRoute: typeof ApiWorkspaceMediaRouteWithChildren
  ApiWorkspaceProfilesRoute: typeof ApiWorkspaceProfilesRouteWithChildren
  ApiWorkspaceStatsRoute: typeof ApiWorkspaceStatsRoute
  ApiWorkspaceStylesRoute: typeof ApiWorkspaceStylesRoute
  ApiImagesComfyAnalyzeRoute: typeof ApiImagesComfyAnalyzeRoute
  ApiWorkspaceFoldersSplatRoute: typeof ApiWorkspaceFoldersSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/harnesses': {
      id: '/api/harnesses'
      path: '/api/harnesses'
      fullPath: '/api/harnesses'
      preLoaderRoute: typeof ApiHarnessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assist/prompts': {
      id: '/api/assist/prompts'
      path: '/api/assist/prompts'
      fullPath: '/api/assist/prompts'
      preLoaderRoute: typeof ApiAssistPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assist/simple': {
      id: '/api/assist/simple'
      path: '/api/assist/simple'
      fullPath: '/api/assist/simple'
      preLoaderRoute: typeof ApiAssistSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/generate': {
      id: '/api/images/generate'
      path: '/api/images/generate'
      fullPath: '/api/images/generate'
      preLoaderRoute: typeof ApiImagesGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/logs': {
      id: '/api/images/logs'
      path: '/api/images/logs'
      fullPath: '/api/images/logs'
      preLoaderRoute: typeof ApiImagesLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/reveal': {
      id: '/api/images/reveal'
      path: '/api/images/reveal'
      fullPath: '/api/images/reveal'
      preLoaderRoute: typeof ApiImagesRevealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/styles': {
      id: '/api/images/styles'
      path: '/api/images/styles'
      fullPath: '/api/images/styles'
      preLoaderRoute: typeof ApiImagesStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/env-default': {
      id: '/api/settings/env-default'
      path: '/env-default'
      fullPath: '/api/settings/env-default'
      preLoaderRoute: typeof ApiSettingsEnvDefaultRouteImport
      parentRoute: typeof ApiSettingsRoute
    }
    '/api/settings/test-endpoint': {
      id: '/api/settings/test-endpoint'
      path: '/test-endpoint'
      fullPath: '/api/settings/test-endpoint'
      preLoaderRoute: typeof ApiSettingsTestEndpointRouteImport
      parentRoute: typeof ApiSettingsRoute
    }
    '/api/settings/test-image-provider': {
      id: '/api/settings/test-image-provider'
      path: '/test-image-provider'
      fullPath: '/api/settings/test-image-provider'
      preLoaderRoute: typeof ApiSettingsTestImageProviderRouteImport
      parentRoute: typeof ApiSettingsRoute
    }
    '/api/workspace/browse': {
      id: '/api/workspace/browse'
      path: '/api/workspace/browse'
      fullPath: '/api/workspace/browse'
      preLoaderRoute: typeof ApiWorkspaceBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/create': {
      id: '/api/workspace/create'
      path: '/api/workspace/create'
      fullPath: '/api/workspace/create'
      preLoaderRoute: typeof ApiWorkspaceCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/files': {
      id: '/api/workspace/files'
      path: '/api/workspace/files'
      fullPath: '/api/workspace/files'
      preLoaderRoute: typeof ApiWorkspaceFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/git': {
      id: '/api/workspace/git'
      path: '/api/workspace/git'
      fullPath: '/api/workspace/git'
      preLoaderRoute: typeof ApiWorkspaceGitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/git-init': {
      id: '/api/workspace/git-init'
      path: '/api/workspace/git-init'
      fullPath: '/api/workspace/git-init'
      preLoaderRoute: typeof ApiWorkspaceGitInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/git-status': {
      id: '/api/workspace/git-status'
      path: '/api/workspace/git-status'
      fullPath: '/api/workspace/git-status'
      preLoaderRoute: typeof ApiWorkspaceGitStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/git-tracked': {
      id: '/api/workspace/git-tracked'
      path: '/api/workspace/git-tracked'
      fullPath: '/api/workspace/git-tracked'
      preLoaderRoute: typeof ApiWorkspaceGitTrackedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/link': {
      id: '/api/workspace/link'
      path: '/api/workspace/link'
      fullPath: '/api/workspace/link'
      preLoaderRoute: typeof ApiWorkspaceLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/media': {
      id: '/api/workspace/media'
      path: '/api/workspace/media'
      fullPath: '/api/workspace/media'
      preLoaderRoute: typeof ApiWorkspaceMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/profiles': {
      id: '/api/workspace/profiles'
      path: '/api/workspace/profiles'
      fullPath: '/api/workspace/profiles'
      preLoaderRoute: typeof ApiWorkspaceProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/stats': {
      id: '/api/workspace/stats'
      path: '/api/workspace/stats'
      fullPath: '/api/workspace/stats'
      preLoaderRoute: typeof ApiWorkspaceStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/styles': {
      id: '/api/workspace/styles'
      path: '/api/workspace/styles'
      fullPath: '/api/workspace/styles'
      preLoaderRoute: typeof ApiWorkspaceStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assist/prompts/$': {
      id: '/api/assist/prompts/$'
      path: '/$'
      fullPath: '/api/assist/prompts/$'
      preLoaderRoute: typeof ApiAssistPromptsSplatRouteImport
      parentRoute: typeof ApiAssistPromptsRoute
    }
    '/api/assist/simple/logs': {
      id: '/api/assist/simple/logs'
      path: '/logs'
      fullPath: '/api/assist/simple/logs'
      preLoaderRoute: typeof ApiAssistSimpleLogsRouteImport
      parentRoute: typeof ApiAssistSimpleRoute
    }
    '/api/harnesses/$id/models': {
      id: '/api/harnesses/$id/models'
      path: '/$id/models'
      fullPath: '/api/harnesses/$id/models'
      preLoaderRoute: typeof ApiHarnessesIdModelsRouteImport
      parentRoute: typeof ApiHarnessesRoute
    }
    '/api/images/comfy/analyze': {
      id: '/api/images/comfy/analyze'
      path: '/api/images/comfy/analyze'
      fullPath: '/api/images/comfy/analyze'
      preLoaderRoute: typeof ApiImagesComfyAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/logs/$': {
      id: '/api/images/logs/$'
      path: '/$'
      fullPath: '/api/images/logs/$'
      preLoaderRoute: typeof ApiImagesLogsSplatRouteImport
      parentRoute: typeof ApiImagesLogsRoute
    }
    '/api/workspace/files/$': {
      id: '/api/workspace/files/$'
      path: '/$'
      fullPath: '/api/workspace/files/$'
      preLoaderRoute: typeof ApiWorkspaceFilesSplatRouteImport
      parentRoute: typeof ApiWorkspaceFilesRoute
    }
    '/api/workspace/folders/$': {
      id: '/api/workspace/folders/$'
      path: '/api/workspace/folders/$'
      fullPath: '/api/workspace/folders/$'
      preLoaderRoute: typeof ApiWorkspaceFoldersSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/media/$': {
      id: '/api/workspace/media/$'
      path: '/$'
      fullPath: '/api/workspace/media/$'
      preLoaderRoute: typeof ApiWorkspaceMediaSplatRouteImport
      parentRoute: typeof ApiWorkspaceMediaRoute
    }
    '/api/workspace/media/from-url': {
      id: '/api/workspace/media/from-url'
      path: '/from-url'
      fullPath: '/api/workspace/media/from-url'
      preLoaderRoute: typeof ApiWorkspaceMediaFromUrlRouteImport
      parentRoute: typeof ApiWorkspaceMediaRoute
    }
    '/api/workspace/profiles/$id': {
      id: '/api/workspace/profiles/$id'
      path: '/$id'
      fullPath: '/api/workspace/profiles/$id'
      preLoaderRoute: typeof ApiWorkspaceProfilesIdRouteImport
      parentRoute: typeof ApiWorkspaceProfilesRoute
    }
    '/api/assist/simple/session/$': {
      id: '/api/assist/simple/session/$'
      path: '/session/$'
      fullPath: '/api/assist/simple/session/$'
      preLoaderRoute: typeof ApiAssistSimpleSessionSplatRouteImport
      parentRoute: typeof ApiAssistSimpleRoute
    }
    '/api/assist/simple/stop/$': {
      id: '/api/assist/simple/stop/$'
      path: '/stop/$'
      fullPath: '/api/assist/simple/stop/$'
      preLoaderRoute: typeof ApiAssistSimpleStopSplatRouteImport
      parentRoute: typeof ApiAssistSimpleRoute
    }
  }
}

interface ApiHarnessesRouteChildren {
  ApiHarnessesIdModelsRoute: typeof ApiHarnessesIdModelsRoute
}

const ApiHarnessesRouteChildren: ApiHarnessesRouteChildren = {
  ApiHarnessesIdModelsRoute: ApiHarnessesIdModelsRoute,
}

const ApiHarnessesRouteWithChildren = ApiHarnessesRoute._addFileChildren(
  ApiHarnessesRouteChildren,
)

interface ApiSettingsRouteChildren {
  ApiSettingsEnvDefaultRoute: typeof ApiSettingsEnvDefaultRoute
  ApiSettingsTestEndpointRoute: typeof ApiSettingsTestEndpointRoute
  ApiSettingsTestImageProviderRoute: typeof ApiSettingsTestImageProviderRoute
}

const ApiSettingsRouteChildren: ApiSettingsRouteChildren = {
  ApiSettingsEnvDefaultRoute: ApiSettingsEnvDefaultRoute,
  ApiSettingsTestEndpointRoute: ApiSettingsTestEndpointRoute,
  ApiSettingsTestImageProviderRoute: ApiSettingsTestImageProviderRoute,
}

const ApiSettingsRouteWithChildren = ApiSettingsRoute._addFileChildren(
  ApiSettingsRouteChildren,
)

interface ApiAssistPromptsRouteChildren {
  ApiAssistPromptsSplatRoute: typeof ApiAssistPromptsSplatRoute
}

const ApiAssistPromptsRouteChildren: ApiAssistPromptsRouteChildren = {
  ApiAssistPromptsSplatRoute: ApiAssistPromptsSplatRoute,
}

const ApiAssistPromptsRouteWithChildren =
  ApiAssistPromptsRoute._addFileChildren(ApiAssistPromptsRouteChildren)

interface ApiAssistSimpleRouteChildren {
  ApiAssistSimpleLogsRoute: typeof ApiAssistSimpleLogsRoute
  ApiAssistSimpleSessionSplatRoute: typeof ApiAssistSimpleSessionSplatRoute
  ApiAssistSimpleStopSplatRoute: typeof ApiAssistSimpleStopSplatRoute
}

const ApiAssistSimpleRouteChildren: ApiAssistSimpleRouteChildren = {
  ApiAssistSimpleLogsRoute: ApiAssistSimpleLogsRoute,
  ApiAssistSimpleSessionSplatRoute: ApiAssistSimpleSessionSplatRoute,
  ApiAssistSimpleStopSplatRoute: ApiAssistSimpleStopSplatRoute,
}

const ApiAssistSimpleRouteWithChildren = ApiAssistSimpleRoute._addFileChildren(
  ApiAssistSimpleRouteChildren,
)

interface ApiImagesLogsRouteChildren {
  ApiImagesLogsSplatRoute: typeof ApiImagesLogsSplatRoute
}

const ApiImagesLogsRouteChildren: ApiImagesLogsRouteChildren = {
  ApiImagesLogsSplatRoute: ApiImagesLogsSplatRoute,
}

const ApiImagesLogsRouteWithChildren = ApiImagesLogsRoute._addFileChildren(
  ApiImagesLogsRouteChildren,
)

interface ApiWorkspaceFilesRouteChildren {
  ApiWorkspaceFilesSplatRoute: typeof ApiWorkspaceFilesSplatRoute
}

const ApiWorkspaceFilesRouteChildren: ApiWorkspaceFilesRouteChildren = {
  ApiWorkspaceFilesSplatRoute: ApiWorkspaceFilesSplatRoute,
}

const ApiWorkspaceFilesRouteWithChildren =
  ApiWorkspaceFilesRoute._addFileChildren(ApiWorkspaceFilesRouteChildren)

interface ApiWorkspaceMediaRouteChildren {
  ApiWorkspaceMediaSplatRoute: typeof ApiWorkspaceMediaSplatRoute
  ApiWorkspaceMediaFromUrlRoute: typeof ApiWorkspaceMediaFromUrlRoute
}

const ApiWorkspaceMediaRouteChildren: ApiWorkspaceMediaRouteChildren = {
  ApiWorkspaceMediaSplatRoute: ApiWorkspaceMediaSplatRoute,
  ApiWorkspaceMediaFromUrlRoute: ApiWorkspaceMediaFromUrlRoute,
}

const ApiWorkspaceMediaRouteWithChildren =
  ApiWorkspaceMediaRoute._addFileChildren(ApiWorkspaceMediaRouteChildren)

interface ApiWorkspaceProfilesRouteChildren {
  ApiWorkspaceProfilesIdRoute: typeof ApiWorkspaceProfilesIdRoute
}

const ApiWorkspaceProfilesRouteChildren: ApiWorkspaceProfilesRouteChildren = {
  ApiWorkspaceProfilesIdRoute: ApiWorkspaceProfilesIdRoute,
}

const ApiWorkspaceProfilesRouteWithChildren =
  ApiWorkspaceProfilesRoute._addFileChildren(ApiWorkspaceProfilesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHarnessesRoute: ApiHarnessesRouteWithChildren,
  ApiSettingsRoute: ApiSettingsRouteWithChildren,
  ApiAssistPromptsRoute: ApiAssistPromptsRouteWithChildren,
  ApiAssistSimpleRoute: ApiAssistSimpleRouteWithChildren,
  ApiImagesGenerateRoute: ApiImagesGenerateRoute,
  ApiImagesLogsRoute: ApiImagesLogsRouteWithChildren,
  ApiImagesRevealRoute: ApiImagesRevealRoute,
  ApiImagesStylesRoute: ApiImagesStylesRoute,
  ApiWorkspaceBrowseRoute: ApiWorkspaceBrowseRoute,
  ApiWorkspaceCreateRoute: ApiWorkspaceCreateRoute,
  ApiWorkspaceFilesRoute: ApiWorkspaceFilesRouteWithChildren,
  ApiWorkspaceGitRoute: ApiWorkspaceGitRoute,
  ApiWorkspaceGitInitRoute: ApiWorkspaceGitInitRoute,
  ApiWorkspaceGitStatusRoute: ApiWorkspaceGitStatusRoute,
  ApiWorkspaceGitTrackedRoute: ApiWorkspaceGitTrackedRoute,
  ApiWorkspaceLinkRoute: ApiWorkspaceLinkRoute,
  ApiWorkspaceMediaRoute: ApiWorkspaceMediaRouteWithChildren,
  ApiWorkspaceProfilesRoute: ApiWorkspaceProfilesRouteWithChildren,
  ApiWorkspaceStatsRoute: ApiWorkspaceStatsRoute,
  ApiWorkspaceStylesRoute: ApiWorkspaceStylesRoute,
  ApiImagesComfyAnalyzeRoute: ApiImagesComfyAnalyzeRoute,
  ApiWorkspaceFoldersSplatRoute: ApiWorkspaceFoldersSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
